# Generated by Django 2.1.4 on 2018-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(null=True, upload_to='blog_img'),
        ),
    ]
